# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tomo-csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 261632bb-d8ab-419d-b0ea-6573935942d5   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: tomo-prod-kv        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    tenantId: 7eeb7a1e-f498-4e8d-b1da-d8fe029a1179                # The tenant ID of the key vault
    enableSecretRotation: "true"
    rotationPollInterval: "1m"
    objects:  |
      array:
        - |
          objectName: mongo-username
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: mongo-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: mongo-keyfile
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: ri-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: google-oauth-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: google-oauth-client-secret
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: mongo-secrets-csi
      type: Opaque
      data:
        - objectName: mongo-username
          key: username
        - objectName: mongo-password
          key: password
    - secretName: redis-secrets-csi
      type: Opaque
      data:
        - objectName: redis-password
          key: password